[[OCaml]]
arch = "aarch64"
git-tree-sha1 = "5d1ff4a0d854bfffdbab042f1dd0c63ec21e96ba"
os = "macos"

    [[OCaml.download]]
    sha256 = "aafcb3f8ea1519a44db11fb73d8d97652f878551f52d9e10621ef9e5122e401c"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+4/OCaml.v5.3.0.aarch64-apple-darwin.tar.gz"
[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "b754d753b00337aa878ba9bd30bdea26e8bc185f"
os = "macos"

    [[OCaml.download]]
    sha256 = "f7d81db3d683dbaff7c8141f7f3e36e37b4a1cc75e07ff39919b47c59b06490d"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+4/OCaml.v5.3.0.x86_64-apple-darwin.tar.gz"
[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "b4c3f807ad68231a864e45b5eb120122e61eb6b4"
libc = "glibc"
os = "linux"

    [[OCaml.download]]
    sha256 = "30fdb7be0aa9a0bece7e43aa32e3233b288141cf4768bf82b7a8b38dca6b3b1b"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+4/OCaml.v5.3.0.x86_64-linux-gnu.tar.gz"
[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "1f4688cc9a86ac0e5e696e6f2eedc1c134c61ff3"
libc = "musl"
os = "linux"

    [[OCaml.download]]
    sha256 = "4ea3b8ccb7cf9ea784804615cc56f09cbf34a0076953c61c8882cc24d2632e3b"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+4/OCaml.v5.3.0.x86_64-linux-musl.tar.gz"
[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "b4ebaa0fca0f2d3f8d6d740c23b3da787e93efc9"
os = "windows"

    [[OCaml.download]]
    sha256 = "91b6442c66a1e7d79176de1df4241d1e609460c7e4121d746cbff916d1943dd1"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+4/OCaml.v5.3.0.x86_64-w64-mingw32.tar.gz"
