[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "d7c5fd9e535c26e135778f5deb30c99abd375616"
libc = "glibc"
os = "linux"

    [[OCaml.download]]
    sha256 = "728a671ea671c41690dfc30982df5339cdec642eb3af969357b8d43c2cc18a24"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+1/OCaml.v5.3.0.x86_64-linux-gnu.tar.gz"
[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "332ae1dbc82056fbeed2395ef3aa54dbf75e0c97"
libc = "musl"
os = "linux"

    [[OCaml.download]]
    sha256 = "931889ce58bc5ad4751ab4ebf760d3ff6ad8aedeae34832db762fe0d7318f46b"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+1/OCaml.v5.3.0.x86_64-linux-musl.tar.gz"
