[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "5df430d18f61bfef0c46c55bab7a26e0801541aa"
libc = "glibc"
os = "linux"

    [[OCaml.download]]
    sha256 = "6cd28ee5271c48e72ecb3296d16dbea1c31a5b3af779de8c97acd59fd231e69b"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+2/OCaml.v5.3.0.x86_64-linux-gnu.tar.gz"
[[OCaml]]
arch = "x86_64"
git-tree-sha1 = "f72253560cd7e7086304f2b380886767c2593783"
libc = "musl"
os = "linux"

    [[OCaml.download]]
    sha256 = "30a86a9dccee1b17e7a7e7990eb20f3c6a5a9aac4240295e2a510e3be461c9f0"
    url = "https://github.com/JuliaBinaryWrappers/OCaml_jll.jl/releases/download/OCaml-v5.3.0+2/OCaml.v5.3.0.x86_64-linux-musl.tar.gz"
