# Autogenerated wrapper script for OCaml_jll for i686-linux-musl
export ocamlc, ocamlopt, ocamlrun

JLLWrappers.@generate_wrapper_header("OCaml")
JLLWrappers.@declare_executable_product(ocamlc)
JLLWrappers.@declare_executable_product(ocamlopt)
JLLWrappers.@declare_executable_product(ocamlrun)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        ocamlc,
        "bin/ocamlc.opt",
    )

    JLLWrappers.@init_executable_product(
        ocamlopt,
        "bin/ocamlopt.opt",
    )

    JLLWrappers.@init_executable_product(
        ocamlrun,
        "bin/ocamlrun",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
