# Autogenerated wrapper script for OCaml_jll for x86_64-linux-gnu
export ocamlc, ocamlopt

JLLWrappers.@generate_wrapper_header("OCaml")
JLLWrappers.@declare_executable_product(ocamlc)
JLLWrappers.@declare_executable_product(ocamlopt)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        ocamlc,
        "bin/ocamlc.opt",
    )

    JLLWrappers.@init_executable_product(
        ocamlopt,
        "bin/ocamlopt.opt",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
