# Autogenerated wrapper script for OCaml_jll for x86_64-w64-mingw32
export ocamlc, ocamlopt, ocamlrun

JLLWrappers.@generate_wrapper_header("OCaml")
JLLWrappers.@declare_executable_product(ocamlc)
JLLWrappers.@declare_executable_product(ocamlopt)
JLLWrappers.@declare_executable_product(ocamlrun)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        ocamlc,
        "bin\\ocamlc.opt.exe",
    )

    JLLWrappers.@init_executable_product(
        ocamlopt,
        "bin\\ocamlopt.opt.exe",
    )

    JLLWrappers.@init_executable_product(
        ocamlrun,
        "bin\\ocamlrun.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
